<?php

namespace AbsencesBundle\Repository;

/**
 * AbsenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbsenceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllAbsences() {
        return $this->createQueryBuilder('q')
            ->getQuery()
            ->getArrayResult();
    }
}
