<?php

namespace AbsencesBundle\Repository;

/**
 * cccRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cccRepository extends \Doctrine\ORM\EntityRepository
{
}
